### ISSUE TITLE
Installation into /usr/local/bin instead /usr/bin/

### ISSUE THREAD

**Issue by eusonlito** [algorich/sublime-url-handler#3]
I think that is more suitable to install `sublime-url-handler` into `/usr/local/bin/` instead `/usr/bin/`.

Regards :)

**Comment by hugomaiavieira** [comment]
I fully agree! Thanks =)

**Comment by zdevel** [comment]
I'm not sure, but I think the last line of the install file needs to change to /usr/local/bin as well.

**Comment by hugomaiavieira** [comment]
@zdevel you are right, my mistake. Thanks =)
